[package]
name = "fleabit"
version = "0.1.2"
edition = "2021"
description = "Read and write unaligned bytes."
license = "MIT OR Apache-2.0"
repository = "https://github.com/gak/fleabit"

[dependencies]
bitvec = "1.0.1"
